# Generated by Django 5.1 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.png', null=True, upload_to='profilepictures'),
        ),
    ]
