# Generated by Django 5.1 on 2024-10-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist_object', 'project_object')},
        ),
    ]
