# Generated by Django 5.1 on 2024-11-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_costumer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
